name: phonenumbers
description: Phone number validation and input widget written in pure dart without any native dependency
version: 0.0.3
homepage: https://github.com/fonibo/phonenumbers

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
